info:
  contact: {}
  license: {}
paths:
  /api/auth/AddAuth:
    post:
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 姓名
        in: query
        name: name
        required: true
        type: string
      - description: 组：crm/calculate
        in: query
        name: group
        required: true
        type: string
      - description: 电话
        in: query
        name: telephone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增个人用户
  /api/exchange/addMyExchange:
    post:
      parameters:
      - description: 申请对象
        in: query
        name: respondent
        required: true
        type: string
      - description: 申请时间
        in: query
        name: request_time
        required: true
        type: string
      - description: 被申请时间
        in: query
        name: requested_time
        required: true
        type: string
      - description: 换班类型，1，晚班，2,周末白班，3，crm工作日特殊班，4，周末全天班
        in: query
        name: exchange_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增本人换班申请表信息
  /api/exchange/deleteAll:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 清空所有的换班请求表
  /api/exchange/deleteMyExchange{id}:
    post:
      parameters:
      - description: Id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除本人的未审批换班请求表
  /api/exchange/examineExchange:
    post:
      parameters:
      - description: Id
        in: query
        name: id
        required: true
        type: integer
      - description: 回复，状态 0为默认、1为拒绝、2为同意
        in: query
        name: response
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 回复换班申请表
  /api/exchange/getAll:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 查看所有的换班请求表
  /api/exchange/getMyExamine:
    post:
      parameters:
      - description: 状态 0：未审批 1：已审批
        in: query
        name: state
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 查看本人回复的换班申请表信息(未审批/已审批)
  /api/exchange/myExchange:
    post:
      parameters:
      - description: 状态 0：未审批 1：已审批
        in: query
        name: state
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 查看本人的换班请求表(未审批/已审批)
  /api/rests/addMyRest:
    post:
      parameters:
      - description: 申请调休时间
        in: query
        name: request_time
        required: true
        type: string
      - description: 申请调休类型，0：上午，1：下午，2：全天
        in: query
        name: type
        required: true
        type: integer
      - description: 申请调休类型，0：调休，1：年休
        in: query
        name: vacation_type
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增本人调休申请表信息
  /api/rests/deleteAll:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除所有调休申请表信息
  /api/rests/deleteMyRest{id}:
    post:
      parameters:
      - description: Id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除本人未审批调休申请表信息
  /api/rests/examineRest:
    post:
      parameters:
      - description: Id
        in: query
        name: id
        required: true
        type: integer
      - description: 回复，状态 0为默认、1为拒绝、2为同意
        in: query
        name: response
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 审批调休申请表
  /api/rests/getAll:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取所有调休申请表信息
  /api/rests/getMe:
    post:
      parameters:
      - description: ' 0 未审批、1 已审批'
        in: query
        name: state
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{rest},"msg":"ok"}'
          schema:
            type: string
      summary: 获取本人调休申请表信息(未审批/已审批)
  /api/rests/getNeedExamine:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 查看需要本人审核的未审核调休申请表信息
  /api/rota/import:
    post:
      parameters:
      - description: excel表格文件
        in: query
        name: file
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 导入值班表
  /api/rotas/addDay:
    post:
      parameters:
      - description: 日期
        in: query
        name: datetime
        required: true
        type: string
      - description: 星期
        in: query
        name: week
        required: true
        type: string
      - description: 计费晚班人员
        in: query
        name: billing_late
        required: true
        type: string
      - description: 计费周末白班人员
        in: query
        name: billing_weekend_day
        required: true
        type: string
      - description: crm晚班人员
        in: query
        name: crm_late
        required: true
        type: string
      - description: crm周末白班人员
        in: query
        name: crm_weekend_day
        required: true
        type: string
      - description: crm工作日特殊班值班人员
        in: query
        name: crm_duty_special
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 添加日值班表
  /api/rotas/deleteDay{datetime}:
    post:
      parameters:
      - description: 日期，例如：2020-09-01
        in: query
        name: datetime
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除日值班表
  /api/rotas/deleteMonth{month}:
    post:
      parameters:
      - description: 月份，例如：2020-09
        in: query
        name: month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除月值班表
  /api/rotas/getMonth{month}:
    post:
      parameters:
      - description: 月份，例如：2020-09
        in: query
        name: month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取当月值班表
  /api/vacation/deleteAll:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 清空所有调休信息
  /api/vacation/deleteByName:
    post:
      parameters:
      - description: 姓名
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除某人调休信息
  /api/vacation/editByName:
    post:
      parameters:
      - description: 姓名
        in: query
        name: name
        required: true
        type: integer
      - description: 剩余调休
        in: query
        name: remain_vacation
        required: true
        type: number
      - description: 剩余年休
        in: query
        name: remain_annual_vacation
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 修改某人调休信息
  /api/vacation/getAll:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取所有员工的调休信息
  /auth:
    post:
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 通过用户名密码获取token
  /register:
    post:
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 名字
        in: query
        name: name
        required: true
        type: string
      - description: 组：crm/calculate
        in: query
        name: group
        required: true
        type: string
      - description: 电话
        in: query
        name: telephone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 注册个人用户
swagger: "2.0"
